"""Added threat_logs table

Revision ID: e41b0ce89ba3
Revises: 1bd904717289
Create Date: 2025-02-17 20:18:24.153121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e41b0ce89ba3'
down_revision: Union[str, None] = '1bd904717289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_threat_logs_id', table_name='threat_logs')
    op.drop_table('threat_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_ip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_alert', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='threat_logs_pkey')
    )
    op.create_index('ix_threat_logs_id', 'threat_logs', ['id'], unique=False)
    # ### end Alembic commands ###
